version: '3.5'
services:
  php-cli:
    build:
      context: docker/php-cli
    volumes:
      - ./:/app
      - ./docker/php-cli/php.ini:/usr/local/etc/php/php.ini
      - ./upload:/upload
    tty: true
    stdin_open: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
